all:
#	$(LATEX) Phys12-C01-g
#	$(LATEX) Phys12-C01-g
#	$(LATEX) Phys12-C01-inclass
#	$(LATEX) Phys12-C01-inclass
	$(LATEX) Phys12-C01-projectileMotion
	$(LATEX) Phys12-C01-projectileMotion
	$(LATEX) Phys12-C01-sigFigs
	$(LATEX) Phys12-C01-sigFigs

clean:
	rm -rf *.log *.aux *.snm *.toc *.nav *.out *.*~ *~
