all:
	xelatex PhysAP1-C12-practiceTest2
	xelatex PhysAP1-C12-practiceTest2
#	xelatex PhysAP1-C14-notice
#	xelatex PhysAP1-C14-notice

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class12
	cp *.pdf $(DESTINATION)/Class12
