all:
	pdflatex Phys11-C15-powerGen
	pdflatex Phys11-C15-powerGen
	pdflatex Phys11-C15-Homework
	pdflatex Phys11-C15-Homework

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class15
	cp *.pdf $(DESTINATION)/Class15
